Objects:
  - животное
  - птица
  - крылья
  - перья
  - страус
  - канарейка
  - маленькая
  - высокий
  - ноги
  - длинные
  - тонкие
  - рыба
  - акула
  - опасна
  - прожорлива
  - яркая
  - нерка
  - плавники
  - жабры
Connection:
 - type: есть
   from_ob: птица
   to_ob: животное

 - type: есть
   from_ob: животное
   to_ob: птица

 - type: есть
   from_ob: рыба
   to_ob: животное

 - type: есть
   from_ob: животное
   to_ob: рыба

 - type: имеет
   from_ob: птица
   to_ob: крылья

 - type: имеет
   from_ob: крылья
   to_ob: птица

 - type: имеет
   from_ob: птица
   to_ob: перья

 - type: имеет
   from_ob: перья
   to_ob: птица

 - type: есть
   from_ob: канарейка
   to_ob: птица

 - type: есть
   from_ob: птица
   to_ob: канарейка

 - type: характеристика
   from_ob: канарейка
   to_ob: маленькая

 - type: характеристика
   from_ob: маленькая
   to_ob: канарейка

 - type: есть
   from_ob: страус
   to_ob: птица

 - type: есть
   from_ob: птица
   to_ob: страус

 - type: характеристика
   from_ob: страус
   to_ob: высокий

 - type: характеристика
   from_ob: высокий
   to_ob: страус

 - type: имеет
   from_ob: страус
   to_ob: ноги

 - type: имеет
   from_ob: ноги
   to_ob: страус

 - type: характеристика
   from_ob: ноги
   to_ob: длинные

 - type: характеристика
   from_ob: длинные
   to_ob: ноги

 - type: характеристика
   from_ob: ноги
   to_ob: тонкие

 - type: характеристика
   from_ob: тонкие
   to_ob: ноги

 - type: характеристика
   from_ob: акула
   to_ob: опасна

 - type: характеристика
   from_ob: опасна
   to_ob: акула

 - type: характеристика
   from_ob: нерка
   to_ob: прожорлива

 - type: характеристика
   from_ob: прожорлива
   to_ob: нерка

 - type: характеристика
   from_ob: нерка
   to_ob: яркая

 - type: характеристика
   from_ob: яркая
   to_ob: нерка

 - type: есть
   from_ob: нерка
   to_ob: рыба

 - type: есть
   from_ob: рыба
   to_ob: нерка

 - type: есть
   from_ob: акула
   to_ob: рыба

 - type: есть
   from_ob: рыба
   to_ob: акула

 - type: имеет
   from_ob: рыба
   to_ob: плавники

 - type: имеет
   from_ob: плавники
   to_ob: рыба

 - type: имеет
   from_ob: рыба
   to_ob: жабры

 - type: имеет
   from_ob: жабры
   to_ob: рыба





